# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98467f3f60fb67391b024f7fb51164197dc47d5be183a60f0bfcec195038bc70a214f30b9fb718b109e517b4f4b43db5556ffc18a75eb88e248f5fbbe152afec

test:
  secret_key_base: 229ccb66048791409d029040525aba80c4cabc9b12340c8733fe6cf25cf5eabb971d93173df032c1899f1e753de4ce774703b03dbe610237b651e616aefd1956

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
